# Generated by Django 3.1.6 on 2021-02-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productq', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['product_ID'],
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('Factory_Name', models.CharField(max_length=500, verbose_name='اسم المنشأه')),
                ('Factory_ID', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='رقم السجل')),
                ('Factory_Address', models.TextField(max_length=500, verbose_name='العنوان')),
                ('Factory_Manger', models.CharField(max_length=100, verbose_name='المدير')),
                ('Mobile_number', models.CharField(max_length=12, verbose_name='رقم الموبايل')),
                ('products', models.ManyToManyField(through='home.Fact_product', to='home.products', verbose_name='المنتجات')),
            ],
        ),
        migrations.AddField(
            model_name='fact_product',
            name='Factory_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.factory'),
        ),
        migrations.AddField(
            model_name='fact_product',
            name='product_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t', to='home.products'),
        ),
        migrations.AddField(
            model_name='fact_product',
            name='units_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ty', to='home.unit'),
        ),
    ]
