# Generated by Django 3.1.6 on 2021-02-20 19:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('Factory_Name', models.CharField(max_length=500)),
                ('Factory_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Factory_Address', models.TextField(max_length=500)),
                ('Factory_city', models.CharField(max_length=50)),
                ('Factory_Manger', models.CharField(max_length=100)),
                ('Factory_Activity', models.CharField(max_length=100)),
                ('Mobile_number', models.CharField(max_length=12)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None)),
                ('Factory_gov', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.gov')),
            ],
        ),
    ]
