# Generated by Django 3.1.6 on 2021-02-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='Factory_Address',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='Factory_ID',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='رقم السجل'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='Factory_Manger',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المدير'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='Factory_Name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='اسم المنشأه'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='Mobile_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='رقم الموبايل'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, through='home.Fact_product', to='home.products', verbose_name='المنتجات'),
        ),
    ]
