# Generated by Django 3.1.6 on 2021-02-26 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210226_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reg',
            name='reqnum',
            field=models.CharField(default='hi', max_length=50),
        ),
        migrations.CreateModel(
            name='Fact_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productq', models.CharField(max_length=50)),
                ('Factory_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.factory')),
                ('product_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.products')),
            ],
        ),
        migrations.AddField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(through='home.Fact_product', to='home.products'),
        ),
    ]
