# Generated by Django 3.1.6 on 2021-02-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210227_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='products',
        ),
    ]
