# Generated by Django 3.1.6 on 2021-02-26 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210226_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact_product',
            name='product_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t', to='home.products'),
        ),
    ]
