# Generated by Django 3.1.6 on 2021-02-27 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_factory_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact_product',
            name='units_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ty', to='home.unit'),
        ),
    ]
